### ISSUE TITLE
Bower Package

### ISSUE THREAD

**Issue by Mte90** [Mte90/MozStrap#1]

**Comment by Ryuno-Ki** [comment]
What shall be done?

Installing Twitter Bootstrap v3 via Bower?

**Comment by Mte90** [comment]
install that theme with bower

**Comment by Ryuno-Ki** [comment]
I've prepared a PR but not submitted it, yet.
I need your help first:
1. Add a License, since [no-license](http://choosealicense.com/no-license/) is not valid [a valid identifier](https://github.com/bower/spec/blob/master/json.md#name)
2. Add a entry point JavaScript file (otherwise you'll run into validation troubles with Bower again, I am afraid. However, there are some WordPress packages which you could sneak into).
3. After PR is submitted, check against the name/description/keywords, please.
